services:

  mysql80:
    image: mysql:8.0
    # (optional) mysql은 컨테이너 이름 설정 불필요
    container_name: mysql80
    networks:
      - esg_local_net
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    # AWS 서버의 절대 경로로 지정
    env_file:
      - /home/ubuntu/env/.env.development
      - /home/ubuntu/env/.env.production
    ports:
      - "3306:3306"
    restart: always

  redis7alpine:
    image: redis:7-alpine
    # (optional) redis는 컨테이너 이름 설정 불필요
    container_name: redis7alpine
    networks:
      - esg_local_net
    restart: always

  ollama:
    image: ollama/ollama
    # (필요) 도커 컨테이너 이름 고정해서 bge-m3 모델 설치 exec 실행 (.github\workflows\main.yml)
    container_name: ollama
    networks:
      - esg_local_net
    volumes:
      - ./ollama:/root/.ollama
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    # AWS 서버의 절대 경로로 지정
    env_file:
      - /home/ubuntu/env/.env.development
      - /home/ubuntu/env/.env.production
    ports:
      - "8000:8000"
    depends_on:
      - mysql80
      - redis7alpine
      - ollama
    restart: always
    networks:
      - esg_local_net

networks:
  esg_local_net:
    driver: bridge
